### ISSUE TITLE
Emit static keyword- and builtin types lists

### ISSUE THREAD

**Issue by oleks** [emerald/emerald#7]
When building the compiler, emit keyword- and builtin types list to enable automatic generation of syntax highlighters. At the very least, provide scripts to generate such lists from source.

**Comment by Athas** [comment]
Does the list of keywords and builtins change frequently in Emerald?

**Comment by oleks** [comment]
> Does the list of keywords and builtins change frequently in Emerald?

No, so better yet, maintain a text file with keywords instead, and generate the necessary part of the compiler from that. I'll get back to that when I can test my builds of the compiler. I don't dare change it, before I can test it.
